// PROGRAMA QUE SE UTILIZA PARA EL EJERCICIO 1-D DEL Proyecto Shields v1.0 GRUPO 2- 2022

#include <Arduino.h>
#include <Wire.h>             // INCLUYO LA LIBRERIA DEL PUERTO I2C

#include <Adafruit_GFX.h>     // INCLUYO LA LIBRERIA  PARA VISULIZAR CARACTERES,(IMAGENES - LETRAS),EN LA PANTALLA 

#include <Adafruit_SSD1306.h> // INCLUYO LA LIBRERIA DEL CONTROLADOR SSD1306 QUE USA LA PANTALLA OLED


#define ANCHO_PANTALLA 128 // DEFINO EN 128 PIXELES EL ANCHO DE LA PANTALLA OLED 
#define ALTO_PANTALLA 64   // DEFINO EN 64 PIXELES EL ALTO DE LA PANTALLA OLED


// OBJETO DE LA CLASE ADAFRUIT_SSD1306 . EL CONSTRUCTOR DE ESTA CLASE ADMITE 4 PARÁMETROS.

Adafruit_SSD1306 display(ANCHO_PANTALLA, ALTO_PANTALLA, &Wire, -1); // SE DEFINE LOS 4 PARAMETROS PARA LA PANTALLA OLED


void setup()
{

  Wire.begin(); // INICIO EL PUERTO I2C
  display.begin(SSD1306_SWITCHCAPVCC, 0x3C); // INICIO LA PANTALLA, SE ACTIVA EL VOLTAJE DE 3,3V INTERNO PARA LA PANTALLA Y  LA DIRECCIÓN I2C QUE UTILIZA LA PANTALLA
  

}

void loop()
{
  display.clearDisplay();      // SE LIMPIA EL CONTENIDO DEL BUFFER DE LA PANTALLA, ES DECIR, SE PONE TODOS LOS PÍXELES A OFF.
  // SE REALIZA LAS CONFIGURACIONES DE LA FUENTE - TEXTO
  display.setTextSize(1);      // SE DEFINE EL TAMAÑO DEL TEXTO, EL 1 INDICA QUE LA LETRA OCUPA UNA ALTURA DE 8 PIXELES
  display.setTextColor(WHITE); // SE DEFINE EL COLOR DEL TEXTO, PARA VISUALIZAR EL MISMO EN LA PANTALLA
  display.setCursor(10, 16);   // SE SITUA EL CURSOR EN LA PANTALLA PARA MOSTRAR EL SIGUIENTE TEXTO
  display.println(" ES FACIL EL  ");// 
  display.setCursor(10, 32);   // SE SITUA EL CURSOR EN LA PANTALLA PARA MOSTRAR EL SIGUIENTE TEXTO
  display.println("    DESARROLLO ");//
  display.setCursor(10, 48);  // SE SITUA EL CURSOR EN LA PANTALLA PARA MOSTRAR EL SIGUIENTE TEXTO
  display.println("  CON SHIELDS "); //
  display.display(); //ENVIO A PANTALLA TODO EL TEXTO
}
